### PR TITLE
added a new distributed systems blog

### PR DESCRIPTION
**Pull request by bohemianjock**

### CODE REVIEW

**Comment by hackerkid** [comment]
Hello Gokul, is https://medium.com/@blockmonk your blog? If yes can you create a GitHub organization/account separately for the blog and use that as the GitHub username instead. I think that would be less confusing for the readers.

**Comment by bohemianjock** [comment]
Ok.

**Comment by bohemianjock** [comment]
I have made the changes

**Comment by hackerkid** [comment]
@bohemianjock I have merged but you would want to add the blog by yourselves by going to diff.blog since this is a personal blog.

**Comment by bohemianjock** [comment]
Okay

**Pull request merged**
