### PR TITLE
Added some awesome blog

### PR DESCRIPTION
**Pull request by megapro17**

### CODE REVIEW

**Comment by diffblog** [comment]
Merged as https://github.com/diffblog/hacktoberfest/commit/5b508ab17ec9973d41c913caa79e9d4fa24e07e4. Thanks!

**Comment by diffblog** [comment]
The blog you added is now live at https://diff.blog/arnonrgo/ :)

**Comment by megapro17** [comment]
That didn't count in hacktoberfest...

**Comment by megapro17** [comment]
Pull requests in repositories with the ‘hacktoberfest’ topic will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify.

**Comment by hackerkid** [comment]
@megapro17 Added the label.

**Pull request closed without merging**
