### PR TITLE
Contributions to software engineering blog

### PR DESCRIPTION
**Pull request by Ousainu**
Added smashingmagazine blog to blogs.json

### CODE REVIEW

**Comment by hackerkid** [comment]
I think you might want to remove the dev.to entry? It looks like a blog post.

**Comment by Ousainu** [comment]
> I think you might want to remove the dev.to entry? It looks like a blog post.

I'll remove it. should i also create another pull request?

**Comment by Ousainu** [comment]
So I just removed the dev.to entry. let me know if there are any more changes you would like to add or remove!

**Comment by hackerkid** [comment]
Thanks a lot for working on this. Merged thanks :)

**Pull request merged**
